### ISSUE TITLE
Strong name signature not valid

### ISSUE THREAD

**Issue by Mefor** [XAMLMarkupExtensions/XAMLMarkupExtensions#97]
Unable to validate 'XAMLMarkupExtensions.dll' strong name:
> sn.exe -vf "XAMLMarkupExtensions.dll" -> Failed to verify assembly -- Strong name validation failed.

It seems like it is related with fact that .dll is signed with 'public.snk' (doesn't have private key) and it is pushed to the Nuget feed without actual strong name signing (with private key). Delay signing step missed from build workflow.

Note:  XAMLMarkupExtensions v. 1.2.1.3 signed correctly.

Assemblies that are unable to pass strong name validation procedure could cause issues (depending on 'strong-name bypass feature' configuration -> [msdn](https://docs.microsoft.com/en-us/dotnet/standard/assembly/disable-strong-name-bypass-feature))

**Comment by martingercke** [comment]
I am having the same problem.
We are thinking of switching to a different library, because we are having security restrictions on the server that we are using this library:
If bypassing of. strong name is not allowed you are running into problems.
If you are setting the following entries in the registry you should be able to reproduce the error.

; Security Settings for .NET
MACHINE\Software\Microsoft\.NETFramework\AllowStrongNameBypass=4,0
MACHINE\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\AllowStrongNameBypass=4,0

Further details can be found here:
[https://docs.microsoft.com/en-us/dotnet/standard/assembly/disable-strong-name-bypass-feature](https://docs.microsoft.com/en-us/dotnet/standard/assembly/disable-strong-name-bypass-feature)

Would be great if you could sign it correctly again, so that usage with. this security parameter will work again!
Thanks in advance!

**Comment by konne** [comment]
@martingercke @Mefor please test the new 2.1 release.
I have changed the signing process so that starting from now the 2.1 is fully signed and for someone who needs an unsigned I also add a second NuGet package.
